version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-2)
      - REPOSITORY_URI=004443144924.dkr.ecr.eu-west-2.amazonaws.com/express-node-app-test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest -f node.dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:dev
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:dev
      - printf '[{"name":"nodeexpresscontainercft","imageUri":"%s"}]' $REPOSITORY_URI:dev > imagedefinitions.json

artifacts:
  files: imagedefinitions.json